name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
    # services: #it is very similiar to docker-compose file
    #   app:
    #     image: ugurozgen/node-api
    #     ports:
    #       - "3001:3000"
    #   mongo:
    #     image: mongo
    #     ports:
    #       - "3001:3000"
    #       - "27017:27017"

    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
