name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6,8,10] # it will trigger 3 different job
      max-parallel: 2 # as default github maximize this number
      fail-fast: true
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
            # node-version: 6
            node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: node -v